--- @type down.mod.ui.icon.Builtin.Icons
return {
  file = {
    default = {
      type = "file",
      icon = "",
      hl = "DownIconDefault",
      default = true,
    },
    directory = {
      type = "directory",
      icon = "",
      hl = "DownIconDirectory",
      default = true,
    },
    file = {
      type = "file",
      icon = "",
      hl = "DownIconFile",
      default = true,
    },
  },
  extension = {
    ["default"] = "",
    ["directory"] = "",
    ["file"] = "",
    ["lua"] = "",
    ["vim"] = "",
    ["c"] = "",
    ["cpp"] = "",
    ["css"] = "",
    ["dockerfile"] = "",
    ["go"] = "",
    ["html"] = "",
    ["java"] = "",
    ["javascript"] = {
      icon = "",
      hl = "Type",
      type = "extension",
    },
    ["json"] = "",
    ["python"] = "",
    ["ruby"] = "",
    ["rust"] = "",
    ["typescript"] = "",
    ["yaml"] = "",
  },
  directory = {
    ["default"] = "",
    ["directory"] = "",
    ["file"] = "",
  },
  lsp = {
    ["default"] = "",
    ["error"] = "",
    ["hint"] = "",
    ["info"] = "",
    ["warning"] = "",
    ["ok"] = "",
    ["unknown"] = "",
    ["c"] = "",
    ["cpp"] = "",
    ["css"] = "",
    ["dockerfile"] = "",
    ["go"] = "",
    ["html"] = "",
    ["java"] = "",
    ["javascript"] = "",
    ["json"] = "",
    ["lua"] = "",
    ["python"] = "",
    ["ruby"] = "",
    ["rust"] = "",
    ["typescript"] = "",
    ["vim"] = "",
    ["yaml"] = "",
  },
}
