--- @meta    down.ids.config
--- @brief   Provides core data types
--- @version <5.2,JIT
---
--- @brief down.config
---
--- The local config for setting up workspaces.
--- @class (exact) down.config.Local workspace config local
---   @field public dir? down.Uri"./.down/" by default
---   @field public init? down.config.Init, optional init
---   metadata?: { [string]?: any },
---
--- Configuration for base directories globally.
--- @class (exact) down.config.Dirs dirs
---   @field public home down.Dir default "~/.down/"
---   @field public config down.Dir default "~/.config/down/"
---   @field public cache down.Dir  default "~/.cache/down/"
---   @field public temp down.Dir default "~/.temp/down/"
---   @field public runtime down.Dir string default "~/.down/runtime/"
---   @field public log down.Dir string default "~/.down/log/"
---
--- Configuration for global settings.
--- @class (exact) down.config.Global: down.Workspaces Down global configuration
---   @field public user down.User used
---   @field public dirs down.config.Dirs dirs
---   @field public workspaces down.Workspace> workspace list
---   @field public mod table<string, down.Mod> mod list
---   @field public config down.Config config
---   @field public [string]? down.Mod modules
---
--- @brief down.config.local
---
--- @brief down.config.global
---
--- @brief down.handlefig.init
---
--- The important store value object
--- @class (exact) down.config.Init Init
---   @field git? down.config.init.Git Git
---   @field sync? down.config.init.Sync sync
---   @field markdown? down.config.init.Markdown sync
---   @field command? down.config.init.Command command
---   @field [string]? down.config.init.Command
---
--- The important store value object
--- @class (exact) down.config.init.Markdown Git init
---   @field public enabled boolean Enable
---
--- The important store value object
--- @class (exact) down.config.init.Git Git init
---   @field public enabled boolean Enable
---
--- The important store value object
--- @class (exact) down.config.init.Command command init
---   @field public enabled? boolean Enable
---   @field public command? string Enable
---   @field public args? string[] Enable
---
--- The important store value object
--- @class (exact) down.config.init.Sync Sync init
---   @field public enabled boolean Enable
---
--- @alias down.config.Toggle
--- | "dev"
--- | "debug"
--- | "bench"
--- | "test"
--- | "defaults
---
--- @alias down.log.Level
--- | "trace"
--- | "debug"
--- | "info"
--- | "warn"
--- | "error"
--- | "fatal"

--- @class (exact) down.log.Config
--- @field plugin string                                           Name of the plugin. Prepended to log messages.
--- @field outfile string
--- @field use_console boolean                                     Whether to print the output to Neovim while running.
--- @field highlights boolean                                      Whether highlighting should be used in console (using `:echohl`).
--- @field use_file boolean                                        Whether to write output to a file.
--- @field level down.log.Level                                          Any messages above this level will be logged.
--- @field modes ({ name: down.log.Level, hl: string, level: number })[] Level config.
--- @field float_precision number                                  Can limit the number of decimals displayed for floats.

--- @class (exact) down.Log
---   @field levels table<string, number>
---   @field number_level table<number, string>
---   @field config down.log.Config
