column_width = 80
space_after_function_names = "Always"
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
no_call_parentheses = false

[sort_requires]
enabled = true
