tools:
    shell:
        allow:
            - cd *
            - lua *
            - "true"
            - luac *
            - echo *
            - find *
            - ls *
            - head *
            - cat *
            - file *
            - go build *
